### ISSUE TITLE
スラッシュを挟んだら「助詞の連続」が適用されないようにして欲しい

### ISSUE THREAD

**Issue by hakohumi** [ics-creative/project-japanese-proofreading#18]
インラインコードでファイルパスを書こうとしたときに、ファイル名によってはlinterに引っかかることがありました。
ファイルパス中の日本語には解析を適用しないようになれば良いなと思いました。

もしくは、既出でしたら申し訳ないのですが、1行だけ解析を無効にするような構文がありましたら、教えていただけると幸いです。

![image](https://user-images.githubusercontent.com/37200171/158087908-9e03e903-699f-4c9e-a9a7-db813f905d6c.png)

**Comment by ghost** [comment]
ご提案ありがとうございます。

長らくお待たせしていましたが、v1.3.0（2023年4月12日リリース）にて、スラッシュを挟んだら「助詞の連続」が適用されないように修正しました。

![スクリーンショット 2023-04-17 15 52 23](https://user-images.githubusercontent.com/78718425/232407940-2f49b410-5038-4f59-bfc2-068ed29e7626.png)
![スクリーンショット 2023-04-17 15 52 42](https://user-images.githubusercontent.com/78718425/232407967-3fb0e927-2d79-401c-a146-abf6822d05d2.png)

また、注意事項として、v1.3.0では**校正ルール「助詞の連続」を初期設定では無効にする**変更をしています。ご利用される際は、プラグインの設定画面からルールを有効に変更いただければと思います。

![スクリーンショット 2023-04-17 15 53 23](https://user-images.githubusercontent.com/78718425/232408678-0130257b-3666-46b4-8766-1887a8bfbbbe.png)
