### ISSUE TITLE
クイックフィックスの実行

### ISSUE THREAD

**Issue by y-marui** [ics-creative/project-japanese-proofreading#19]
いつもありがとうございます。
「従って => したがって」のように文字の置き換えを支持する場合は、
クイックフィックスで修正が実行できる様になるとありがたいです。
ざっと見た感じでは、実装されていないと思いますが、勘違いであれば申し訳ありません。
したの画像は、VS Codeのものです。

<img width="461" alt="スクリーンショット 2022-03-28 11 10 44" src="https://user-images.githubusercontent.com/12211343/160314795-5017e7c0-6389-4579-986b-cec8c16a1802.png">

**Comment by ghost** [comment]
ご提案ありがとうございます。

長らくお待たせしていましたが、v1.3.0（2023年4月12日リリース）にてクイックフィックス機能をリリースしました。
修正可能なエラーに対して、クイックフィックスが利用できるようになりましたので、ぜひご活用いただければと思います。

▼クイックフィックスが有効なエラー

![スクリーンショット 2023-04-17 15 18 03](https://user-images.githubusercontent.com/78718425/232400466-5a5ecfc0-ac76-4cad-bb8f-902a27185532.png)

![スクリーンショット 2023-04-17 15 21 24](https://user-images.githubusercontent.com/78718425/232401316-898a148c-a33c-4d96-9dd9-d93b0ebfc2db.png)
