### ISSUE TITLE
「ですます」調と「である」調の指摘が機能していない

### ISSUE THREAD

**Issue by takeyamada** [ics-creative/project-japanese-proofreading#21]
## 手順：
1. vscode(バージョン: 1.61.0 (Universal))を開き、拡張子の検索部分で「テキスト校正くん」を入力
2. テキスト校正くん(バージョン:0.2.3)の拡張子が表示されたので、インストールを行なった。
3. vscodeの再起動を行い、a.txtを作成した。
4. a.txtに下記載にある2種類の入力例を作成して、校正が行われるか試してみた。
   4-1. 私は、お土産でいただいたりんごを美味しいと思います。みかんも美味しかったです。しかし、他の人は、美味しいと思わない。
   4-2. りんごとみかんをお土産でいただきました。それらのフルーツは、新鮮である。

## 実際結果：
4-1と4-2の2種類の例どちらでも、エラーを吐かなかった。
4-1の実行結果:
<img width="412" alt="スクリーンショット 2022-04-27 14 06 13" src="https://user-images.githubusercontent.com/44803977/165444603-f4fd9aa1-a224-49ca-96b9-1be34df215b5.png">
4-2の実行結果:
<img width="761" alt="スクリーンショット 2022-04-27 14 04 51" src="https://user-images.githubusercontent.com/44803977/165444514-7c7da197-5b03-4fdc-9556-ee6d75d0577e.png">

## 期待結果：
どちらも、「ですます」調と「である」調が混在しているため、エラーを吐いてほしい。

## 余談 :
コミットログ(https://github.com/ics-creative/project-japanese-proofreading/commit/83ec782069b1d3b1c37254c373b9ee5f47701e42) で修正されたと書かれていますが、「ですます」調と「である」調の校正機能のことではありませんでしょうか。

**Comment by ics-furudate** [comment]
ご報告ありがとうございます。
また、返答を長らくお待たせしており失礼しました。

報告の通り、v0.2.3では「ですます」調と「である」調の校正機能が動作していない問題がありました。
この問題は、v1.0.0（2022年3月2日リリース）で修正しましたので、プラグインをバージョンアップいただくことで改善されると思います。

注意事項として、テキスト校正くんの仕様上、「である」調の判定は**明らかに常体な「〜である」のみ**となっています。そのため、いただいた4-1の入力例はエラーとはなりません。

![スクリーンショット 2023-02-08 19 41 58](https://user-images.githubusercontent.com/78718425/217507334-6bb50153-4198-455f-9837-29a81273db2e.png)

この仕様がわかりにくいという課題がありますが、先のバージョンで補足を追記することを予定しています。
本Issueの問題は、v1.0.0（2022年3月2日リリース）にて改善されたと思いますので、クローズとさせてください。
