### ISSUE TITLE
入力例のドキュメントが欲しいです

### ISSUE THREAD

**Issue by takeyamada** [ics-creative/project-japanese-proofreading#22]
## 目的：
不具合が発生したときに、環境依存の問題か文章として検知できないかを判断するために、例文があるとわかりやすいと思いました。

## 現在検出してくれない機能の例：
- 2重否定 : その解答は、正しくないこともない。
- 「ですます」調と「である」調の混在：りんごとみかんをお土産でいただきました。それらのフルーツは、新鮮であった。
- 同じ接続詞の連続使用：今日は、朝から友達と一緒に勉強した。そして、お昼頃に、一度勉強を中止して公園で遊び始めた。そして、夕方頃、勉強を再開した。

## 現在検出してくれる機能の例：
- ら抜き言葉: なんでも自分で決めれる。
- 全角と半角アルファベットの混在:ＡBCD
- 同じ助詞の連続使用：AだけどBだけどC
- ウェブの用語や名称の表記統一（Javascript→JavaScript、Github→GitHub等）: Github
- 漢字の閉じ方、開き方: ジュースがこぼれたので、ティッシュを下さい
- 読点の数：私は、ダイエットをしており、3カ月で10ｋg減量したが、あっという間にリバウンドをしてしまい、またダイエットをしなくてはんならなくなった。
- 「が」の連続使用:日本には、水質がきれいな湖が3カ所あるが、海外では存在するだろうか。

## その他
- 同じ助詞の連続使用の部分は、反応する助詞と反応しない助詞がありました。(上手くいく例:AだけどBだけどC。失敗例:私の兄のお気に入りのレストランに行った。)
- 全角と半角アルファベットの混在：小文字の場合は、反応しないけど、大文字は反応している。(失敗例:ｇggggg)
- [Upstream](https://github.com/textlint-ja/textlint-rule-no-doubled-conjunction)であるtextlint-rule-no-doubled-conjunction
で、同じ接続詞の連続使用を試すために用意されていた例文「かな漢字変換により漢字が、多用される傾向がある。しかし、漢字の多用が読みにくさをもたらす側面は否定できない。しかし、平仮名が多い文は間延びした印象を与える恐れもある。」を試したが、この例文でも上手く検知しなかった。

**Comment by ics-nishihara** [comment]
@takeyamada 
ご報告ありがとうございます。
NGになる、[入力例のドキュメント](https://github.com/ics-creative/project-japanese-proofreading/blob/master/EXAMPLES.md)を用意しました。

二重否定について不具合で動作していなかったため修正しました。

ですます調についてですが、誤検出の回避のためもあり判定は明らかに常体な「〜である」のみとなっています。そのため、

> りんごとみかんをお土産でいただきました。それらのフルーツは、新鮮であった。

のような文章は検出されません。

以上、ご確認よろしくお願いいたします。

**Comment by ics-ikeda** [comment]
本件は上記のとおり、入力例のドキュメントを用意していますので、Issueとしてクローズいたします。
