### ISSUE TITLE
"jft-style/4.3.2.大かっこ「」" をGUI上で無効にできない

### ISSUE THREAD

**Issue by mistbind3u88** [ics-creative/project-japanese-proofreading#24]
## 概要

掲題の指摘事項に関して無効化するためのトグルがGUI上確認できない。

![image](https://user-images.githubusercontent.com/18084560/166745841-f86259d7-a958-4774-903e-0e8daa99d7d1.png)

## 要望

「プラグイン一覧/詳細 > 拡張機能の設定 > 設定一覧」に大かっこに対する指摘を表示し、GUI上から無効化可能にする。

![image](https://user-images.githubusercontent.com/18084560/166748016-cc17e0ba-d8dd-454a-9a87-5c09d695791d.png)

## 暫定対応

setting.jsonに丸かっこに対する設定を無効化する記述を追加し、これを手動で大かっこに対する設定に書き換える事で暫定的に対応可能でした。

```json
{
  "japanese-proofreading.textlint.丸かっこ（）": false,
  "japanese-proofreading.textlint.大かっこ［］": false
}
```

**Comment by mistbind3u88** [comment]
取り急ぎ、確認した事象とそれに対する暫定対応を纏めましたのでご参考下さい。

**Comment by mistbind3u88** [comment]
VSCodeのプラグイン周りの仕様に明るくないのですが、ざっと見た感じVSCodeのGUI上で設定を可能にする、package.jsonの「configuration>properties」中にrule.tsに含まれている指摘事項への対応項目が存在しないことが原因ではないでしょうか。

https://github.com/ics-creative/project-japanese-proofreading/blob/7c073c44d8b9b6f541e56daeb898fb49bbdd25c4/package.json#L164-L168

**Comment by ics-nishihara** [comment]
@mistbind3u88 
 ご報告と検証コードありがとうございます。
v1.2.0（2023年2月8日リリース）より大かっこの設定を無効化するGUIを用意しました。

プラグインのアップデートにより設定の変更が可能です。
よろしくお願いいたします。

![スクリーンショット 2023-02-08 15 11 39](https://user-images.githubusercontent.com/48976682/217449301-434e4b52-8435-4dcc-8366-63755e1a8535.png)
