### ISSUE TITLE
校正が実行されるtxtファイルがプレーンテキストのみになっている。

### ISSUE THREAD

**Issue by margariaks** [ics-creative/project-japanese-proofreading#28]
.txtファイルを開き、以下の言語モードにて確認したことを記載します。
・txt
　校正機能が実行されない。
・プレーンテキスト
　校正機能が実行される
・小説家になろう（拡張機能「テキスト小説」にて追加されます）
　校正機能が実行されない。
・青空文庫（拡張機能「テキスト小説」にて追加されます）

issues #21 の手順のうち、「a.txtを作成する」をVScode内にて行った場合、作成されたa.txtの言語モードは「txt」となっています。
VScode標準の「txt」言語モードへ対応して頂きたいです。

**Comment by ics-furudate** [comment]
本GitHubにIssueでご報告いただきありがとうございます。
ご連絡いただいた件について返答します。

> ・txt
>　校正機能が実行されない。

社内メンバーで確認したところ、VS Codeの標準機能から「txt」という言語モードを確認することができず再現できませんでした。確認したところ「プレーンテキスト」という言語モードは存在しますが、「txt」という言語モードは存在しませんでした。
拡張機能をすべて無効にした状態でも再現されるか、いま一度ご確認いただけないでしょうか。

![2023-01-16 19 32 55](https://user-images.githubusercontent.com/78718425/212658744-79645838-5672-4c62-97a8-271d28d5d80d.png)


> ・小説家になろう（拡張機能「テキスト小説」にて追加されます）
> ・青空文庫（拡張機能「テキスト小説」にて追加されます）

他拡張機能による言語モード（「小説家になろう」「青空文庫」の言語モード）は、テキスト校正くんでサポートを行っていないため、申し訳ございませんが対応を見送らせていただけたらと思います。

本件は2023年1月23日までにご回答いただければ幸いです。どうぞよろしくお願いします。

**Comment by margariaks** [comment]
お世話になっております。
当方の環境にて確認したところ、導入している「Txt Syntax」という拡張機能にて「.TXT」という言語モードを参照していることが判明しました。
起票時の記載にて「.txt」と表記しておりましたが正しくは「.TXT」でした。失礼いたしました。

調査して頂きありがとうございました。
また、お手数をおかけし、申し訳ございません。

上記のことから、プレーンテキストではなく、なんらかの「.txt」拡張子を独自の言語モードで参照している拡張機能ではテキスト校正くんは動作しないと解釈しておりますが、相違ないでしょうか？

**Comment by ics-furudate** [comment]
返答、ご確認ありがとうございます。

「.TXT」は、拡張機能で独自に追加された言語モードということで承知しました。

> 上記のことから、プレーンテキストではなく、なんらかの「.txt」拡張子を独自の言語モードで参照している拡張機能ではテキスト校正くんは動作しないと解釈しておりますが、相違ないでしょうか？

はい、その認識でお間違いありません。
「.txt」拡張子でテキスト校正くんを利用される際は、恐れ入りますが言語モードを「プレーンテキスト」に変更してご利用いただけたらと思います。
