### ISSUE TITLE
`japanese-proofreading.textlint.句点(。)と読点(、)`オプションを無効にしても句読点のカンマ・ピリオドが指摘される

### ISSUE THREAD

**Issue by hajime0316** [ics-creative/project-japanese-proofreading#5]
**What is the problem?**

日本語文章の句読点にカンマとピリオドを使いたくて，カンマとピリオドを指摘されない設定を行おうとした．setting.jsonにおいて`japanese-proofreading.textlint.句点(。)と読点(、)`を`false`に設定したが，相変わらず句読点のカンマとピリオドが指摘される．`japanese-proofreading.textlint.技術用語`を`false`に設定すると，カンマとピリオドは指摘されなくなった．ただ，私は`japanese-proofreading.textlint.技術用語`の機能を使いつつ，句読点のカンマとピリオドの指摘だけなくしたいが，それが出来ない．

**How can I reproduce it?**

1. setting.jsonに，`"japanese-proofreading.textlint.句点(。)と読点(、)": false,`を記述
2. 日本語で書かれた句読点がカンマ・ピリオドの文章をVS Codeで確認
    - この段階では，句読点のカンマ・ピリオドに指摘が入る．
3. setting.jsonに`"japanese-proofreading.textlint.技術用語": false,`を記述
4. 日本語で書かれた句読点がカンマ・ピリオドの文章をVS Codeで確認
    - この段階で，句読点のカンマ・ピリオドに指摘が入らなくなる．

**Is there any error message in the console?**

`japanese-proofreading.textlint.技術用語`有効時に，VS Codeの「問題」に以下のような表示が出る．

```error
． => 。
カンマとコンマではなく句点読点を使います（技術用語）（prh）
```

**Environment**

- Operating system: Windows10
- VSCode version: 1.36.1
- テキスト校正くんのversion: 0.2.2

**Comment by ics-ikeda** [comment]
ご要望頂き増してありがとうございます。
また、長らく返答できておらず失礼しました。

本件は、拡張機能に設定項目を設けることで対応しました。「テキスト校正くん」（VSCode拡張機能）のv1.1.0で利用できます。

![image](https://user-images.githubusercontent.com/975273/156746335-dd3a9328-eeed-448f-99fb-9a84d29862ba.png)

以下の項目で、有効と無効を切り替えることができます。
Textlint: ピリオドとカンマの使用（全角）
Textlint: ピリオドとカンマの使用（半角）


▼設定オプションを有効（デフォルト状態）

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/975273/156746057-4aa7d809-bfa4-4026-9861-c4240e1c0443.png">

▼設定オプションを無効

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/975273/156746220-fc9c0996-ac65-4e36-a880-9a9ad87edc5b.png">


こちらで、元のご要望は反映できたと思いますので、Issueはクローズとさせてください。
ご提案いただきましてありがとうございました。
